(define (move-containers-to-platform n weights)
	(let* ((total (apply + weights))
				 (limit (/ (* 3 total) 4))
				 (source weights)
				 (middle '())
				 (target '())
				 (mid-weight 0)
				 (failed? #f)
				 (step 0))
		(define (platform-ref name)
			(cond ((eq? name 'source) source)
						((eq? name 'middle) middle)
						((eq? name 'target) target)
						(else '())))
		(define (platform-set! name value)
			(cond ((eq? name 'source) (set! source value))
						((eq? name 'middle) (set! middle value))
						((eq? name 'target) (set! target value))
						(else #f)))
		(define (legal-place? weight stack)
			(or (null? stack) (< weight (car stack))))
		(define (print-move weight from to)
			(set! step (+ step 1))
			(display "Step ")
			(display step)
			(display ": move ")
			(display weight)
			(display " from ")
			(display from)
			(display " to ")
			(display to)
			(newline)
			(display "Middle platform weight: ")
			(display mid-weight)
			(newline))
		(define (end-to-end? from to)
			(or (and (eq? from 'source) (eq? to 'target))
					(and (eq? from 'target) (eq? to 'source))))
		(define (move-one from to)
			(if failed?
					#f
					(let ((from-stack (platform-ref from))
								(to-stack (platform-ref to)))
						(if (end-to-end? from to)
								(set! failed? #t)
								(if (null? from-stack)
										(set! failed? #t)
										(let ((w (car from-stack)))
											(if (not (legal-place? w to-stack))
													(set! failed? #t)
													(begin
														(platform-set! from (cdr from-stack))
														(platform-set! to (cons w to-stack))
														(cond ((eq? to 'middle) (set! mid-weight (+ mid-weight w)))
																((eq? from 'middle) (set! mid-weight (- mid-weight w)))
																(else #f))
														(print-move w from to)
														(if (> mid-weight limit)
																(set! failed? #t)
																#f)))))))))
		;; Linear Tower of Hanoi: only adjacent moves are allowed.
		(define (move-adjacent k from to other)
			(if (and (not failed?) (> k 0))
					(begin
						(move-end (- k 1) from other to)
						(move-one from to)
						(move-adjacent (- k 1) other to from))
					#f))
		(define (move-end k from to middle)
			(if (and (not failed?) (> k 0))
					(begin
						(move-end (- k 1) from to middle)
						(move-one from middle)
						(move-end (- k 1) to from middle)
						(move-one middle to)
						(move-end (- k 1) from to middle))
					#f))
		(display "Total weight: ")
		(display total)
		(newline)
		(display "Middle platform limit: ")
		(display limit)
		(newline)
		(move-adjacent n 'source 'middle 'target)
		(if (not failed?)
				(move-adjacent n 'middle 'target 'source)
				#f)
		(if failed?
				(display "FAILURE")
				(display "SUCCESS"))
		(newline)))

(define (run-tests)
	(newline)
	(display "Test 1")
	(newline)
	(move-containers-to-platform 5 '(20 30 50 60 80))
	(newline)
	(display "Test 2")
	(newline)
	(move-containers-to-platform 4 '(10 25 40 70))
	(newline)
	(display "Test 3")
	(newline)
	(move-containers-to-platform 6 '(15 22 35 48 70 90))
	(newline))

(run-tests)
